[config]
schemaVersion = "0.0.1"

[package]
namespace = "DIBS"
name = "DIBS"
versionNumber = "1.0.0"
description = "Defend Items (from) Being Stolen"
websiteUrl = "https://github.com/joeyvanlierop/DIBS"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.19"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../zip"

[[build.copy]]
source = "../CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["mods", "tweaks"]