# https://github.com/xoxfaby/BetterUI/blob/master/.github/workflows/build-and-release.yml
name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./dotnet.yml

  release-thunderstore:
    needs: build
    uses: ./thunderstore.yml
    with:
      version: ${{ needs.build.outputs.version }}
    secrets:
      THUNDERSTORE_TOKEN: ${{ secrets.THUNDERSTORE_TOKEN }}

  release-github:
    needs: release-thunderstore
    uses: ./release.yml