# https://github.com/xoxfaby/actions/blob/main/.github/workflows/dotnet-publish.yml
name: .NET Deploy

on:
  workflow_call:
    outputs:
      version:
        description: "Version as determined by GitVersion"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.MajorMinorPatch }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Setup Bin Cache
        uses: actions/cache@v3.6.0
        with:
          path: ./bin
          key: bin-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Setup NuGet Cache
        uses: actions/cache@v3.6.0
        with:
          path: ./nuget
          key: nuget-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          additionalArguments: "/updateprojectfiles"

      - name: Update Version
        run: sed -i "s/public const string Version = \".*\"/public const string Version = \"${{ steps.gitversion.outputs.MajorMinorPatch }}\"/" DIBS/DIBS.cs

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Publish
        run: dotnet publish --no-build -c Release

      - name: Pack
        run: dotnet pack -o ./nuget --no-build -c Release