# https://github.com/xoxfaby/actions/blob/main/.github/workflows/dotnet.yml
name: .NET

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          additionalArguments: "/updateprojectfiles"

      - name: Update Version
        run: sed -i "s/public const string Version = \".*\"/public const string Version = \"${{ steps.gitversion.outputs.MajorMinorPatch }}.${{ github.run_number }}\"/" DIBS/DIBS.cs


      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: BetterUI
          path: ./bin/Release/netstandard2.0/*.dll