# https://github.com/xoxfaby/actions/blob/main/.github/workflows/thunderstore.yml
name: Thunderstore Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      THUNDERSTORE_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install TCLI
        run: dotnet tool install --global tcli --version 0.1.4

      - name: Get Bin Cache
        uses: actions/cache@v3
        with:
          path: ./bin
          key: bin-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Setup Zip Cache
        uses: actions/cache@v3
        with:
          path: ./zip
          key: zip-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Release
        run: tcli publish --token ${{ secrets.THUNDERSTORE_TOKEN }} --package-version ${{ inputs.version }} --config-path ./Thunderstore/thunderstore.toml